import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('zain_jaffri2live.com');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email' }).fill('zain_jaffri@live.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('user4321');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('checkbox', { name: 'Simple Transfer' }).check();
  await page.getByText('Out of State Title').click();
  await page.getByRole('checkbox', { name: 'Simple Transfer' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Multiple Transfer' }).check();
  await page.getByText('Number of Transfers:').click();
  await page.getByRole('checkbox', { name: 'Multiple Transfer' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Duplicate Title' }).check();
  await page.getByRole('heading', { name: 'Missing Title Reason' }).click();
  await page.getByRole('checkbox', { name: 'Duplicate Title' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Duplicate Registration' }).check();
  await page.getByRole('heading', { name: 'Transaction Details' }).click();
  await page.getByRole('checkbox', { name: 'Duplicate Registration' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Duplicate Stickers' }).check();
  await page.getByRole('heading', { name: 'THE ITEM REQUESTED WAS' }).click();
  await page.locator('div').filter({ hasText: /^Duplicate StickersMonthYear$/ }).getByLabel('Duplicate Stickers').uncheck();
  await page.getByRole('checkbox', { name: 'Duplicate Plates & Stickers' }).check();
  await page.getByRole('heading', { name: 'License Plate' }).click();
  await page.getByRole('checkbox', { name: 'Duplicate Plates & Stickers' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Add Lienholder' }).check();
  await page.getByText('With Title').click();
  await page.getByRole('checkbox', { name: 'Add Lienholder' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Remove Lienholder' }).check();
  await page.getByRole('heading', { name: 'Lien Release' }).click();
  await page.getByRole('checkbox', { name: 'Remove Lienholder' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Name Change' }).check();
  await page.getByRole('heading', { name: 'Name Statement (Ownership' }).click();
  await page.getByRole('checkbox', { name: 'Name Change' }).nth(2).uncheck();
  await page.getByRole('checkbox', { name: 'Change of Address' }).check();
  await page.getByRole('heading', { name: 'Previous Residence or' }).click();
  await page.getByRole('checkbox', { name: 'Change of Address' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Filing for Planned Non-' }).check();
  await page.getByRole('heading', { name: 'PLANNED NON-OPERATION CERTIFICATE' }).click();
  await page.getByRole('checkbox', { name: 'Filing for Planned Non-' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Restoring PNO Vehicle to' }).check();
  await page.getByRole('heading', { name: 'Vehicle Information' }).click();
  await page.getByRole('checkbox', { name: 'Restoring PNO Vehicle to' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Certificate of Non-Operation' }).check();
  await page.getByRole('heading', { name: 'Vehicle Storage Location' }).click();
  await page.getByRole('checkbox', { name: 'Certificate of Non-Operation' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Personalized Plates' }).check();
  await page.getByTestId('personalized-plates-order').nth(1).check();
  await page.getByRole('heading', { name: 'SELECT CONFIGURATION' }).click();
  await page.getByTestId('personalized-plates-order').nth(1).uncheck();
  await page.getByTestId('personalized-plates-replace').nth(1).check();
  await page.getByRole('heading', { name: 'FOR REPLACEMENT ONLY' }).click();
  await page.getByTestId('personalized-plates-reassign/retain').nth(1).check();
  await page.getByRole('heading', { name: 'REASSIGN, RETAIN INTEREST, OR' }).click();
  await page.getByTestId('personalized-plates-exchange').nth(1).check();
  await page.getByRole('heading', { name: 'PLATE SELECTION' }).click();
  await page.getByRole('checkbox', { name: 'Personalized Plates' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Disabled Person Placards/' }).check();
  await page.getByRole('heading', { name: 'Type of Disabled Person' }).click();
  await page.getByRole('checkbox', { name: 'Disabled Person Placards/' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Commercial Vehicle' }).check();
  await page.getByText('I\'ll start using this vehicle').click();
  await page.getByRole('checkbox', { name: 'Commercial Vehicle' }).nth(1).uncheck();
  await page.getByRole('checkbox', { name: 'Salvage' }).check();
  await page.getByRole('heading', { name: 'Salvage Certificate' }).click();
  await page.getByRole('checkbox', { name: 'Salvage' }).nth(1).uncheck();
});