import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('zain_jaffri@live.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('user4321');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('checkbox', { name: 'Simple Transfer' }).check();
  await page.getByRole('textbox', { name: 'Vehicle/ Hull Identification' }).click();
  await page.getByRole('textbox', { name: 'Vehicle/ Hull Identification' }).fill('123456789');
  await page.getByRole('textbox', { name: 'First Name' }).first().click();
  await page.getByRole('textbox', { name: 'First Name' }).first().fill('Saneha');
  await page.getByRole('textbox', { name: 'Middle Name' }).first().click();
  await page.getByRole('textbox', { name: 'Middle Name' }).first().fill('Hello');
  await page.getByRole('textbox', { name: 'Last Name' }).first().click();
  await page.getByRole('textbox', { name: 'Last Name' }).first().fill('Kitty');
  await page.getByRole('textbox', { name: 'Street' }).first().click();
  await page.getByRole('textbox', { name: 'Street' }).first().fill('Sm street');
  await page.getByRole('textbox', { name: 'First Name' }).nth(1).click();
  await page.getByRole('textbox', { name: 'First Name' }).nth(1).fill('No name');
  await page.getByRole('textbox', { name: 'Middle Name' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).nth(1).fill('Gehe');
  await page.getByRole('textbox', { name: 'Last Name' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Last Name' }).nth(1).fill('Hello');
  await page.getByRole('textbox', { name: 'Print Name(s)' }).click();
  await page.getByRole('textbox', { name: 'Print Name(s)' }).fill('SANEHa');
  await page.getByRole('textbox', { name: 'Appointee Name(s)' }).click();
  await page.getByRole('textbox', { name: 'Appointee Name(s)' }).fill('BILAl');
  await page.getByRole('button', { name: 'Save' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Continue Anyway' }).click();
  const page1 = await page1Promise;
  await page.getByRole('link', { name: 'Search Transactions' }).click();
  await page.getByRole('row', { name: '/29/2025, 6:07:53 AM Simple Transfer' }).getByRole('button').first().click();
  await page.getByRole('textbox', { name: 'Vehicle/ Hull Identification' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).first().click();
  await page.getByRole('textbox', { name: 'First Name' }).nth(1).click();
  await page.getByRole('button', { name: 'Save' }).click();
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Continue Anyway' }).click();
  const page2 = await page2Promise;
});