import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('zain_jaffri@live.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('user4321');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('checkbox', { name: 'Add Lienholder' }).check();
  await page.getByRole('checkbox', { name: 'With Title' }).check();
  await page.getByRole('textbox', { name: 'Vehicle/ Hull Identification' }).click();
  await page.getByRole('textbox', { name: 'Vehicle/ Hull Identification' }).fill('hello');
  await page.getByRole('textbox', { name: 'Vehicle/ Hull Identification' }).dblclick();
  await page.getByRole('textbox', { name: 'Vehicle/ Hull Identification' }).fill('123456');
  await page.getByRole('textbox', { name: 'Vehicle License Plate or' }).click();
  await page.getByRole('textbox', { name: 'Vehicle License Plate or' }).fill('642428324');
  await page.getByRole('textbox', { name: 'Make of Vehicle OR Vessel' }).click();
  await page.getByRole('textbox', { name: 'Make of Vehicle OR Vessel' }).fill('37y42');
  await page.getByRole('textbox', { name: 'Year of Vehicle' }).click();
  await page.getByRole('textbox', { name: 'Year of Vehicle' }).fill('4723');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Saneha');
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('Fhbwejef');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Whjfgyjew');
  await page.locator('div').filter({ hasText: /^Driver License NumberStateState$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'State' }).first().click();
  await page.getByText('Alaska').click();
  await page.getByRole('textbox', { name: 'Driver License Number' }).click();
  await page.getByRole('textbox', { name: 'Driver License Number' }).fill('46278346');
  await page.getByRole('textbox', { name: 'Street' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Street' }).nth(1).fill('bfhew');
  await page.getByRole('textbox', { name: 'APT./SPACE/STE.#' }).nth(1).click();
  await page.getByRole('textbox', { name: 'APT./SPACE/STE.#' }).nth(1).fill('642');
  await page.locator('div').filter({ hasText: /^CityStateStateZIP Code$/ }).getByPlaceholder('Zip Code').click();
  await page.locator('div').filter({ hasText: /^CityStateStateZIP Code$/ }).getByPlaceholder('Zip Code').fill('37648');
  await page.getByRole('button', { name: 'State', exact: true }).click();
  await page.getByText('Alaska').click();
  await page.locator('div').filter({ hasText: /^CityStateAKZIP Code$/ }).getByPlaceholder('City').click();
  await page.locator('div').filter({ hasText: /^CityStateAKZIP Code$/ }).getByPlaceholder('City').fill('jarachi');
  await page.locator('div').filter({ hasText: /^CityStateAKZIP Code$/ }).getByPlaceholder('City').press('ArrowLeft');
  await page.locator('div').filter({ hasText: /^CityStateAKZIP Code$/ }).getByPlaceholder('City').press('ArrowLeft');
  await page.locator('div').filter({ hasText: /^CityStateAKZIP Code$/ }).getByPlaceholder('City').press('ArrowLeft');
  await page.locator('div').filter({ hasText: /^CityStateAKZIP Code$/ }).getByPlaceholder('City').press('ArrowLeft');
  await page.locator('div').filter({ hasText: /^CityStateAKZIP Code$/ }).getByPlaceholder('City').press('ArrowLeft');
  await page.locator('div').filter({ hasText: /^CityStateAKZIP Code$/ }).getByPlaceholder('City').press('ArrowLeft');
  await page.locator('div').filter({ hasText: /^CityStateAKZIP Code$/ }).getByPlaceholder('City').fill('Karachi');
  await page.getByRole('button', { name: 'Save' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Continue Anyway' }).click();
  const page1 = await page1Promise;
  await page.getByRole('link', { name: 'Search Transactions' }).click();
  await page.getByRole('row', { name: '3/29/2025, 6:17:20 AM Lien' }).getByRole('cell').nth(1).click();
});