import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SenerioProvider } from "../Contexts/SenerioContext";
import { AuthContextProvider } from "../Contexts/AuthContext";
import NavWrapper from "../Layouts/header/NavWrapper";
import StripeProvider from "../Contexts/PaymentContext";
import { Toaster } from "react-hot-toast";
import { ConfirmProvider } from "@/Contexts/ConfirnContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FormMatic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ConfirmProvider>
          <AuthContextProvider>
            <StripeProvider>
              <SenerioProvider>
                <NavWrapper />
                {children}
              </SenerioProvider>
            </StripeProvider>
          </AuthContextProvider>
        </ConfirmProvider>
        {/* 🔔 Toast provider for global popups */}
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
