import {
    PDFDocument,
    PDFTextField,
    PDFCheckBox,
    PDFRadioGroup,
} from 'pdf-lib';

const buildFieldMapping = (formData) => {
    return {
        "Text1": "Text1",
        "Text2": "Text2",
        "Text3": "Text3",
        "Text4": "Text4",
        "Text5": "Text5",
        "Text6": "Text6",
        "Text7": "Text7",
        "Text8": "Text8",
        "Text9": "Text9",
        "Text10": "Text10",
        "Text11": "Tx11",
        "Text12": "Text12",
        "Text13": "Text13",
        "Text14": "Text14",
        "Group1": true,
        'IDENTIFICATION NUMBER': formData.vehicleInfoState?.['Vehicle/Hull Identification Number'] || "-",
        'YEAR MODEL': formData.vehicleInfoState?.['Year of Vehicle'] || "-",
        'MAKE': formData.vehicleInfoState?.['Make of Vehicle OR Vessel Builder'] || "-",
        'LICENSE PLATE/CF NO': formData.vehicleInfoState?.['Vehicle License Plate or Vessel CF Number'] || "-",
        'MOTORCYCLE ENGINE NUMBER': formData.vehicleInfoState?.['Motorcycle Engine Number'] || '-',
        'I/We': `${formData.ownersData?.[0]?.['First Name'] || '-'} ${formData.ownersData?.[0]?.['Last Name'] || ''}`,
        'to': `${formData.newOwnerData?.[0]?.['First Name'] || '-'} ${formData.newOwnerData?.[0]?.['Last Name'] || ''}`,
        "PRINTBUYER'S": formData.transactionSelections?.includes('Vehicle is a Gift') ? formData.newOwnerData[0]?.['Relationship with Gifter'] : '-',
        "Explain odometer discrepancy": "Explain odometer discrepancy",
        "PRINT BUYER'S NAME": `${formData.newOwnerData?.[0]?.['First Name'] || '-'} ${formData.newOwnerData?.[0]?.['Last Name'] || ''}`,
        'Purchase price': formData.newOwnerData?.[0]?.['6 Purchase Price/Market Value'] || "-",
        'SIGNATUREx': "",
        'DATE': "DATE",
        'DL/ID OR DEALER/DISM #': formData.newOwnerData?.[0]?.['Driver License Number'] || '-',
        "PRINT BUYER'S NAME_1": `${formData.newOwnerData?.[1]?.['First Name'] || '-'} ${formData.newOwnerData?.[1]?.['Last Name'] || ''}`,
        "SIGNATUREx_1": "",
        "DATE_1": "DATE_1",
        "DL/ID OR DEALER/DISM #_1": formData.newOwnerData?.[1]?.['Driver License Number'] || '-',
        "PRINT BUYER'S NAME_2": `${formData.newOwnerData?.[2]?.['First Name'] || '-'} ${formData.newOwnerData?.[2]?.['Last Name'] || ''}`,
        'SIGNATUREx_2': "",
        'DATE_2': "DATE_2",
        'DL/ID OR DEALER/DISM #_2': formData.newOwnerData?.[2]?.['Driver License Number'] || '-',
        'DAYTIME TELEPHONE NO': formData.newOwnerData?.[0]?.['Phone Number'] || '-',
        "PRINTSELLER'S NAME": `${formData.ownersData?.[0]?.['First Name'] || '-'} ${formData.ownersData?.[0]?.['Last Name'] || ''}`,
        'SIGNATUREx_3': "",
        'DATE_3': "DATE_3",
        'DL/ID OR DEALER/DISM #_3': formData.ownersData?.[0]?.['Driver License Number'] || '-',
        "PRINT SELLER'S NAME": `${formData.ownersData?.[1]?.['First Name'] || '-'} ${formData.ownersData?.[1]?.['Last Name'] || ''}`,
        'SIGNATUREx_4': "",
        'DATE_4': "DATE_4",
        'DL/ID OR DEALER/DISM #_4': formData.ownersData?.[1]?.['Driver License Number'] || '-',
        "PRINT SELLER'S NAME_1": `${formData.ownersData?.[2]?.['First Name'] || '-'} ${formData.ownersData?.[2]?.['Last Name'] || ''}`,
        'SIGNATUREx_5': "",
        'DATE_5': "DATE_5",
        'DL/ID OR DEALER/DISM #_5': formData.ownersData?.[2]?.['Driver License Number'] || '-',
        'DAYTIME TELEPHONE NO_1': formData.ownersData?.[0]?.['Phone Number'] || '-',
        'I/We_1': formData.powerOfAttorneyData?.appointer || '-',
        'SECTION 5 -POWER OF ATTORNEY': "SECTION 5 -POWER OF ATTORNEY",
        'appoint': formData.powerOfAttorneyData?.appointee || '-',
        'DATE_6': "DATE_6",
        'DATE_7': "DATE_7",
        'CheckBox': true,
        'CheckBox_1': true,
        'CheckBox_2': true,
        'text_60czib': formData.newOwnerMailingAddress?.Street === "" ? formData.newOwnerAddress?.Street || '-' : formData.newOwnerMailingAddress?.Street || '-',
        'text_61pxrx': formData.newOwnerMailingAddress.City === "" ? formData.newOwnerAddress.City || '-' : formData.newOwnerMailingAddress.City || '-',
        'text_62cqaf': formData.newOwnerMailingAddress.State === "" ? formData.newOwnerAddress.State || '-' : formData.newOwnerMailingAddress.State || '-',
        'text_63psgg': formData.newOwnerMailingAddress?.["ZIP Code"] === "" ? formData.newOwnerAddress?.["ZIP Code"] || '-' : formData.newOwnerMailingAddress?.["ZIP Code"] || '-',
        'text_64xthv': formData.ownerAddress?.isMailingDifferent === false ? formData.ownerAddress?.residential?.["ZIP Code"] || '-' : formData.ownerAddress?.mailing?.["ZIP Code"] || '-',
        'text_65bzof': formData.ownerAddress?.isMailingDifferent === false ? formData.ownerAddress?.residential?.State || '-' : formData.ownerAddress?.mailing?.State || '-',
        'text_66evl': formData.ownerAddress?.isMailingDifferent === false ? formData.ownerAddress?.residential?.City || '-' : formData.ownerAddress?.mailing?.City || '-',
        'text_67vkky': formData.ownerAddress?.isMailingDifferent === false ? formData.ownerAddress?.residential?.["Street"] || '-' : formData.ownerAddress?.mailing?.["Street"] || '-',
        'click to': "click to",
        'click to 1': "click to 1",
        'App for': "App for",
        'App for2': "App for2",
        'License Plate/CF Number1': "License",
        'Vehicle/Vessel ID/Number1': "Vehicle/Vessel ID",
        'Year/Make': "Year/Make",
        '1 True Full Name, Last': "1 True Full Name, Last",
        '1 DL/ID Number-1.0': "1",
        '1 DL/ID Number-1.1': "2",
        '1 DL/ID Number-1.2': "3",
        '1 DL/ID Number-1.3': "4",
        '1 DL/ID Number-1.4': "5",
        '1 DL/ID Number-1.5 ': "5",
        '1 DL/ID Number-1.6': "7",
        '1 DL/ID Number-1.7': "8",
        'state.1': "AZ",
        "state.0": "NY",
        "1 True Full Name, Last-2": "1 True Full Name, Last-2",
        "1 DL/ID Number-2.0": "5",
        "1 DL/ID Number-2.1": "6",
        "1 DL/ID Number-2.2": "7",
        "1 DL/ID Number-2.3": "8",
        "1 DL/ID Number-2.4": "9",
        "1 DL/ID Number-2.5": "1",
        "1 DL/ID Number-2.6": "2",
        "1 DL/ID Number-2.7.0": "3",
        "1 Residence or Business Address.0": "1 Residence or Business Address.0",
        "1 Apt/Space Number-1": "1 Apt/Space Number-1",
        "1 City-1": "1 City-1",
        "1 States1": "CA",
        "1 Zip Code-1": "1 Zip Code-1",
        "County of residence": "County of residence",
        "1 Mailing Address": "1 Mailing Address",
        "1 Apt/Space Number-2": "1 Apt/Space Number-2",
        "1 City-2": "1 City-2",
        "1 States2": "AZ",
        "1 Zip Code-2.0": "1 Zip Code-2.0",
        "Name of bank, finance company, or individual having a lien on this vehicle": "Name of bank, finance company, or individual having a lien on this vehicle",
        "2 Address": "2 Address",
        "2 Apt/Space Number": "2 Apt/Space Number",
        "2 City": "2 City",
        "2 States1": "AK",
        "2 Zip Code": "2 Zip Code",
        "Check Box1": "Check Box1",
        "Check Box2": "Check Box2",
        "Check Box6": "Check Box6",
        "Check Box4": "Check Box4",
        "Check Box5": "Check Box5",
        "3 Print Name Legal Owner.0": "3 Print Name Legal Owner.0",
        "3 Print Name Legal Owner.1": "3 Print Name Legal Owner.1",
        "3 Print Name Legal Owner.2.0": "3 Print Name Legal Owner.2.0",
        "3 Date.0": "3 Date.0",
        "area code.0": "+1",
        "area code.1": "+1",
        "3 Daytime Phone Number": "7876543245",
        "date.0": "date.0",
        "date.1": "date.1",
        "date.123": "date.123",
        "area": "+1",
        "4 Daytime Phone Number 1": "8764532156",
        "4 Date-2": "4 Date-2",
        "area23": "+1",
        "4 Daytime Phone Number 2.0": "7654332456",
        "4 Daytime Phone Number 2.1": "0987654321",
        "Printed name of authorized agent signing for company": "Printed name of authorized agent signing for company",
        "title of authorized agent signing for company": "title of authorized agent signing for company",
        "License Plate/CF Number122": "test123",
        "Vehicle/Vessel ID/Number211": "test465",
        "Year/Make2": "Year/Make2",
        "6 Purchase Price/Market Value": "12",
        "Date Purchased": "34",
        "Acquired Yr": "2024",
        "Purchase price": "Purchase price",
        "Gift Box": "Gift Box",
        "Gift Box1": "Gift Box1",
        "market value": "market value",
        "true full name of new owner, last, first, middle, suffix, business name, or lessor": "true full name of new owner, last, first, middle, suffix, business name, or lessor",
        "6 DL/ID Card Numer-1.0.0": "9",
        "6 DL/ID Card Numer-1.0.1.0": "8",
        "6 DL/ID Card Numer-1.0.1.1": "7",
        "6 DL/ID Card Numer-1.0.1.2": "6",
        "6 DL/ID Card Numer-1.0.1.3": "5",
        "6 DL/ID Card Numer-1.0.1.4": "4",
        "6 DL/ID Card Numer-1.0.1.5": "3",
        "6 DL/ID Card Numer-1.0.1.6": "2",
        "6 DL/ID Card Numer-1.0.1.7": "1",
        "6 DL/ID Card Numer-1.1": "0",
        "6 DL/ID Card Numer-1.2": "9",
        "6 DL/ID Card Numer-1.3": "8",
        "6 DL/ID Card Numer-1.4": "7",
        "6 DL/ID Card Numer-1.5": "6",
        "6 DL/ID Card Numer-1.6": "5",
        "6 DL/ID Card Numer-1.7.0": "4",
        "6 DL/ID Card Numer-1.7.": "3",
        "And Box.0": "And Box.0",
        "And Box.1": "And Box.1",
        "And Box1.0": "And Box1.0",
        "And Box1.1": "And Box1.1",
        "6 Name First-1": "6 Name First-1",
        "6 state": "OH",
        "6 Name Last-2": "6 Name Last-2",
        "6 DL/ID CArd Number-2.0": "1",
        "6 DL/ID CArd Number-2.1": "2",
        "6 DL/ID CArd Number-2.2": "3",
        "6 DL/ID CArd Number-2.3": "4",
        "6 DL/ID CArd Number-2.4": "5",
        "6 DL/ID CArd Number-2.5": "6",
        "6 DL/ID CArd Number-2.6": "7",
        "6 DL/ID CArd Number-2.7": "7",
        "state-2.8": "28",
        "physical residence or business address.0": "physical residence or business address.0",
        "6 Apt/Space Number-1": "6 Apt/Space Number-1",
        "6 City-1": "6 City-1",
        "6 States1": "61",
        "6 Zip Code-1": "6 Zip Code-1",
        "county residence or county where vehicle or vessle is princi.0": "county residence or county where vehicle or vessle is princi.0",
        "Equipment number. Optional": "Equipment number. Optional",
        "6 Mailing Address": "6 Mailing Address",
        "6 Apt/Space Number-2": "6 Apt/Space Number-2",
        "6 City-2": "6 City-2",
        '6 States 2.0': '20',
        '6 Zip Code-2.0': '6 Zip Code-2.0',
        'Lessee address, if different from address above': 'Lessee address, if different from address above',
        'Vessel or trailer coach principally kept at, address or location if different from physical/business address above': 'Vessel or trailer coach principally kept at, address or location if different from physical/business address above',
        'county.0.0': 'county.0.0',
        '6 area code 1': '+1',
        'daytime telephone number': '78654321',
        'date 2': 'date 2',
        'area code 2': '+1',
        'daytime number 2': '09876543',
        'date 3': 'date 3',
        'area code 3': 'ar3',
        'daytime number 3': '56578899',
        '7 Name New Legal Owner': '7 Name New Legal Owner',
        '7 ELT #.0': '7 ELT #.0',
        '7 ELT #.1.0': '7 ELT #.1.0',
        '7 ELT #.1.1': '7 ELT #.1.1',
        'Physical residence or business address.0': 'Physical residence or business address.0',
        '7 Apt/Space Number.0': '7 Apt/Space Number.0',
        '7 Apt/Space Number.1': '7 Apt/Space Number.1',
        '7 City.0': '7 City.0',
        '7 City.1': '7 City.1',
        '7 State.0': '02',
        '7 State.1': '01',
        '7 Zip Code.0': '7 Zip Code.0',
        '7 Zip Code.1': '7 Zip Code.1',
        'mailing address': 'mailing address',
        "10 Name of Dealership-1": "10 Name of Dealership-1",
        "10 Name of Buyer -1": "10 Name of Buyer -1",
        "10 Date Sold-1": "10 Date Sold-1",
        "10 R/S Number-1.0": "1",
        "10 R/S Number-1.1": "0",
        "10 R/S Number-1.2": "2",
        "10 R/S Number-1.3": "3",
        "10 R/S Number-1.4": "4",
        "10 R/S Number-1.5": "5",
        "10 R/S Number-1.6": "6",
        "10 Print Name Dealer Agent-1": "10 Print Name Dealer Agent-1",
        "10 Dealer Number-1": "10 Dealer Number-1",
        "10 Salesperson Number-1.0": "0",
        "10 Salesperson Number-1.1": "1",
        "10 Salesperson Number-1.2": "2",
        "10 Salesperson Number-1.3": "3",
        "10 Salesperson Number-1.4": "4",
        "10 Salesperson Number-1.5": "5",
        "10 Salesperson Number-1.6": "6",
        "10 Name of Dealership-2": "10 Name of Dealership-2",
        "10 Name of Buyer -2": "10 Name of Buyer -2",
        "10 Date Sold-2": "10 Date Sold-2",
        "10 R/S Number-2.0": "0",
        "10 R/S Number-2.1": "1",
        "10 R/S Number-2.2": "2",
        "10 R/S Number-2.3": "3",
        "10 R/S Number-2.4": "4",
        "10 R/S Number-2.5": "5",
        "10 R/S Number-2.6": "6",
        "10 Print Name Dealer Agent-2": "10 Print Name Dealer Agent-2",
        "10 Dealer Number-2": "10 Dealer Number-2",
        "10 Salesperson Number-2.0": "0",
        "10 Salesperson Number-2.1": "1",
        "10 Salesperson Number-2.2": "2",
        "10 Salesperson Number-2.3": "3",
        "10 Salesperson Number-2.4": "4",
        "10 Salesperson Number-2.5": "5",
        "10 Salesperson Number-2.6": "6",
        "Family transfer box": "Family transfer box",
        "addition/deletion box": "addition/deletion box",
        "gift box": "gift box",
        "Court order box": "Court order box",
        "inheritance box": "inheritance box",
        "Current Market Value 1": "CurrentM",
        "Biennial Smog cert box": "Biennial Smog cert box",
        "Powered by box": "Powered by box",
        "Powered by electricity box": "Powered by electricity box",
        "Powered by diesel box": "Powered by diesel box",
        "Powered by other box": "Powered by other box",
        "Powered by other 2": "Powered by other 2",
        "Paren, grandparent, etc box": "Paren, grandparent, etc box",
        "Companies leasing vehicle box": "Companies leasing vehicle box",
        "Lessor/Lessee of vehicle box": "Lessor/Lessee of vehicle box",
        "Lessor/lessee operator box": "Lessor/lessee operator box",
        "Transfer only box": "Transfer only box",
        "Title only box": "Title only box",
        "Disabled Person Plate": "Disabled Person Plate",
        "Disabled Vet Plate": "Disabled Vet Plate",
        "Disabled Person Placard": "Disabled Person Placard",
        "Window decal-License No": "Window decal-License No",
        "Window decal-Vehicle Make": "Window decal-Vehicle Make",
        "Window decal-Veh ID No": "Window decal-Veh ID No",
        "Mail to-Name": "Mail to-Name",
        "Mail to-Address": "Mail to-Address",
        "Mail to-City": "Mail to-City",
        "Mail to-State": "CA",
        "Mail to-Zip": "Mail to-Zip",
        "UNLADEN WEIGHT": "UNLADEN WEIGHT",
        "PRINTED NAME": "PRINTED NAME",
        "FIRST NAME": "FIRST NAME",
        "MIDDLE NAME": "MIDDLE NAME",
        "App sign area code": "App",
        "App sign phone no": "App sign phone no",
        "Signature date": "Signature date",
        "click to": "click to",
        "License Plate/CF Number": "License Plate/CF Number",
        "Veh/Vessel ID Number": "Veh/Vessel ID Number",
        "Year/Make2": "Year/Make2",
        "click": "click",
        "click to 1": "click to 1",
        "text_71uait": "text_71uait",
        "text_72rrpr": "text_72rrpr",
        "text_73xplb": "text_73xplb",
        "text_74udmw": "text_74udmw",
        "text_75ujtd": "text_75ujtd",
        "checkbox_76urox": "checkbox_76urox",
        "checkbox_77lxng": "checkbox_77lxng",
        "checkbox_78tyvm": "checkbox_78tyvm",
        "textarea_69crqf": "textarea_69crqf",
        "text_70ywcs": "text_70ywcs",
        "text_71qeb": "text_71qeb",
        "text_72cghv": "text_72cghv",
        "text_73edpt": "text_73edpt",
        "text_74aiyr": "text_74aiyr",
        "text_75aiwg": "text_75aiwg",
        "checkbox_76bcix": "checkbox_76bcix",
        "checkbox_80yjyf": "checkbox_80yjyf",
        "checkbox_81iyuu": "checkbox_81iyuu",
        "checkbox_82vosg": "checkbox_82vosg",
        "text_70xghh": "text_70xghh",
        "text_71tqjp": "text_71tqjp",
        "text_72knux": "text_72knux",
        "Text1.0": "Text1.0",
        "Text1.1": "Text1.1",
        "Text1.2": "Text1.2",
        "Text1.3": "Text1.3",
        "Text1.4": "Text1.4",
        "Text1.5": "Text1.5",
        "Text1.6": "Text1.6",
        "Text1.7": "Text1.7",
        "Text1.8": "Text1.8",
        "Text1.9": "Text1.9",
        "Text1.10": "Text1.10",
        "Text1.11": "Text1.11",
        "Text1.12": "Text1.12",
        "Text1.13": "Text1.13",
        "Text1.14": "Text1.14",
        "Text1.15": "Text1.15",
        "Text1.16": "Text1.16",
        "Text1.17": "Text1.17",
        "Text2": "Text2",
        "Text3": "Text3",
        "Text4": "Text4",
        "Text5": "Text5",
        "Text6": "Text6",
        "Text7": "Text7",
        "Text8": "Text8",
        "Check Box9": "Check Box9",
        "Check Box10": "Check Box10",
        "Check Box11": "Check Box11",
        "Check Box12": "Check Box12",
        "Check Box13": "Check Box13",
        "Text14": "Text14",
        "Text15": "Text15",
        "Check Box16": "Check Box16",
        "Check Box17": "Check Box17",
        "Check Box18": "Check Box18",
        "Check Box19": "Check Box19",
        "Text20": "Text20",
        "Text21": "Text21",
        "Check Box22": "Check Box22",
        "Check Box23": "Check Box23",
        "Text24": "Text24",
        "Text25.0.0": "Text25.0.0",
        "Text25.0.1": "Text25.0.1",
        "Text25.0.2": "Text25.0.2",
        "Text25.0.3": "Text25.0.3",
        "Text25.0.4": "Text25.0.4",
        "Text25.0.6": "Text25.0.6",
        "Text25.0.7": "Text25.0.7",
        "Text25.1.0": "Text25.1.0",
        "Text25.1.1": "Text25.1.1",
        "Text25.1.2": "Text25.1.2",
        "Text25.1.3": "Text25.1.3",
        "Text25.1.4": "Text25.1.4",
        "Text25.1.5": "Text25.1.5",
        "Text25.1.6": "Text25.1.6",
        "Text25.1.7": "Text25.1.7",
        "Text25.2.0": "Text25.2.0",
        "Text25.2.1": "Text25.2.1",
        "Text25.2.2": "Text25.2.2",
        "Text25.2.3": "Text25.2.3",
        "Text25.2.4": "Text25.2.4",
        "Text25.2.5": "Text25.2.5",
        "Text25.2.6": "Text25.2.6",
        "Text25.2.7": "Text25.2.7",
        "Text25.05": "Text25.05",
        "Text26": "Text26",
        "Text27": "Text27",
        "Text28": "Text28",
        "Check Box29": "Check Box29",
        "Check Box30": "Check Box30",
        "Text31": "Text31",
        "Check Box32": "Check Box32",
        "Check Box33": "Check Box33",
        "Text34": "Text34",
        "Text35": "Text35",
        "Text36": "Text36",
        "Text37": "Text37",
        "Text38": "Text38",
        "Text39": "Text39",
        "Text40": "Text40",
        "Text41": "Text41",
        "Text42": "Text42",
        "Text43": "Text43",
        "Text44": "Text44",
        "Text45": "Text45",
        "Text46": "Text46",
        "Text47": "Text47",
        "Text48": "Text48",
        "Check Box49": "Check Box49",
        "Check Box50": "Check Box50",
        "Text51.0": "Text51.0",
        "Text51.1": "Text51.1",
        "Text51.2": "Text51.2",
        "Text51.3": "Text51.3",
        "Text51.4": "Text51.4",
        "Text51.5": "Text51.5",
        "Check Box52": "Check Box52",
        "Check Box53": "Check Box53",
        "Check Box54": "Check Box54",
        "Text55": "Text55",
        "Text56.0": "Text56.0",
        "Text56.1": "Text56.1",
        "Text56.2": "Text56.2",
        "Text56.3": "Text56.3",
        "Text56.4": "Text56.4",
        "Text56.5": "Text56.5",
        "Text56.6": "Text56.6",
        "Text56.7": "Text56.7",
        "Text56.8": "Text56.8",
        "Text56.9": "Text56.9",
        "Text56.10": "Text56.10",
        "Text56.11": "Text56.11",
        "Text56.12": "Text56.12",
        "Text56.13": "Text56.13",
        "Text56.14": "Text56.14",
        "Text56.15": "Text56.15",
        "Text56.16": "Text56.16",
        "Text56.17": "Text56.17",
        "Text57": "Text57",
        "Text58": "Text58",
        "Text59": "Text59",
        "Text61": "Text61",
        "Text60": "Text60",
        "Check Box62": "Check Box62",
        "Check Box63": "Check Box63",
        "Check Box64": "Check Box64",
        "Check Box65": "Check Box65",
        "Check Box66": "Check Box66",
        "Check Box67": "Check Box67",
        "Check Box68": "Check Box68",
        "Check Box69": "Check Box69",
        "Text70": "Text70",
        "Text71": "Text71",
        "Text72": "Text72",
        "Check Box73": "Check Box73",
        "Check Box74": "Check Box74",
        "Check Box75": "Check Box75",
        "Check Box76": "Check Box76",
        "Text77": "Text77",
        "Check Box78": "Check Box78",
        "Check Box79": "Check Box79",
        "Text80": "Text80",
        "Check Box81": "Check Box81",
        "Check Box82": "Check Box82",
        "Check Box83": "Check Box83",
        "Text84": "Text84",
        "Check Box85": "Check Box85",
        "Check Box86": "Check Box86",
        "Check Box87": "Check Box87",
        "Check Box88": "Check Box88",
        "Check Box89": "Check Box89",
        "Check Box90": "Check Box90",
        "Check Box91": "Check Box91",
        "Check Box92": "Check Box92",
        "Check Box93": "Check Box93",
        "Check Box94": "Check Box94",
        "Check Box95": "Check Box95",
        "Text96": "Text96",
        "Text97": "Text97",
        "Text98": "Text98",
        "Text99": "Text99",
        "Text100": "Text100",
        "Text101": "Text101",
        "Text102": "Text102",
        "Text103": "Text103",
        "Text104": "Text104",
        "Text105": "Text105",
        "Text106": "Text106",
        "Text107": "Text107",
        "Text108": "Text108",
        'Lessee address': 'Lessee address',
        'lessee': 'lessee',
        'lessee city': 'lessee city',
        'lessee state': 'lessee state',
        'lessee zip code': 'lessee zip code',
        'Trailer coach only': 'Trailer coach only',
        'trailer coach': 'trailer coach',
        'Trailer coach': 'Trailer coach',
        'Trailer coach zip code': 'Trailer coach zip code',
        'Legal owner physical address': 'Legal owner physical address',
        'Legal owner apt number': 'Legal owner apt number',
        'Legal owner city': 'Legal owner city',
        'Legal owner state': 'Legal owner state',
        'Legal owner zip code': 'Legal owner zip code',
        'Legal owner mailing address': 'Legal owner mailing address',
        'Legal owner mailing apt number': 'Legal owner mailing apt number',
        'Legal owner mailing city': 'Legal owner mailing city',
        'Legal owner mailing state': 'Legal owner mailing state',
        'Legal owner mailing zip code': 'Legal owner mailing zip code',
        'Check Box109': 'Check Box109',
        'Date of Operation': 'Date of Operation',
        'Day of Operation': 'Day of Operation',
        'Year of Operation': 'Year of Operation',
        'Date of Work': 'Date of Work',
        'Day went to work': 'Day went to work',
        'Year went to work': 'Year went to work',
        'Date of purchase': 'Date of purchase',
        'Day of purchase': 'Day of purchase',
        'year of purchase': 'year of purchase',
        'Text9.2': '2',
        'Text9.3': '3',
        'Text9.4': '4',
        'Text9.5': '5',
        'Text9.6': '6',
        'Text9.7': '7',
        'Text9.8': '8',
        'Text9.9': '9',
        'Text9.10': '0',
        'Text9.11': '1',
        'Text9.12': '2',
        'Text9.13': '3',
        'Text9.14': '4',
        'Text9.15': '5',
        'Text9.16': '6',
        'Text9.17': '7',
        'Text9.18': '8',
        'Text9.1': '1',
        'Text12': '2',
        'Text10': '0',
        'Text11': '1',
        'Text13': '3',
        'Text16': '6',
        'Text17': '7',
        'Text18': '8',
        'Check Box20': 'Check Box20',
        'Check Box24': 'Check Box24',
        'Check Box25': 'Check Box25',
        'Check Box26': 'Check Box26',
        'Check Box27': 'Check Box27',
        'Text29': 'Text29',
        'Text30': 'Text30',
        'Check Box31': 'Check Box31',
        'Check Box34': 'Check Box34',
        'Check Box35': 'Check Box35',
        'Check Box36': 'Check Box36',
        'Text49': 'Text49',
        'Text50': 'Text50',
        'Check Box51': 'Check Box51',
        'Check Box55': 'Check Box55',
        'Text62': 'Text62',
        'Text64': '64',
        'Check Box70': 'Check Box70',
        'Check Box71': 'Check Box71',
        'Text73': 'Text73',
        'Text74': '74',
        'Text75': '75',
        'Check Box77': 'Check Box77',
        'Check Box80': 'Check Box80',
        'Text81': 'Text81',
        'Text82': 'Text82',
        'Text83': 'Text83',
        'Text85': 'Text85',
        'Text86': '86',
        'Text87': '87',
        'Text88': 'Text88',
        'Text89': 'Text89',
        'Text90': 'Text90',
        'Text91': 'Text91',
        'Text92': 'Text92',
        'Text93': '93',
        'Text94': 'Tex94',
        'Text95': 'Text95',
        'Text109': 'Text109',
        'Text110': 'Text110',
        'Text111': '11',
        'Text112': 'Tx112',
        'Text113': 'Text113',
        'Text115': 'Text115',
        'Text116': '16',
        'Text117': 'Tx117',
        'Text118': 'Text118',
        'Text119': 'Text119',
        'Text120': 'Text120',
        'Text121': 'Text121',
        'Text122': 'Text122',
        'Text123': '23',
        'Text124': 'Tx124',
        'Text125': 'Text125',
        'Text126': '26',
        'Text127': 'Text127',
        'Text128': '28',
        'Text129': 'Tx129',
        'Check Box130': 'Check Box130',
        'Check Box131': 'Check Box131',
        'Text132.0': '0',
        'Text132.1': '1',
        'Text132.2': '2',
        'Text132.3': '3',
        'Text132.4': '4',
        'Text132.5': '5',
        'Check Box133': 'Check Box133',
        'Check Box134': 'Check Box134',
        'Check Box135': 'Check Box135',
        'Text136': 'Text136',
        'Text137': 'Text137',
        'Text138': 'Text138',
        'Text139': 'Text139',
        'Check Box140': 'Check Box140',
        'Text141': 'Text141',
        'Text142': 'Text142',
        'Text143': 'Text143',
        'Text144': 'Text144',
        'Text145': 'Text145',
        'Text146': 'Text146',
        'Text147': 'Text147',
        'Text148': 'Text148',
        'Text149': 'Text149',
        'Check Box150': 'Check Box150',
        'Check Box151': 'Check Box151',
        'Check Box152': 'Check Box152',
        'Check Box153': 'Check Box153',
        'Check Box154': 'Check Box154',
        'Check Box155': 'Check Box155',
        'Text156': 'Text156',
        'Check Box157': 'Check Box157',
        'Text158': 'Text158',
        'Check Box159': 'Check Box159',
        'Text160': 'Text160',
        'Check Box161': 'Check Box161',
        'Check Box162': 'Check Box162',
        'Check Box163': 'Check Box163',
        'Check Box164': 'Check Box164',
        'Text165': 'Text165',
        'Check Box166': 'Check Box166',
        'Check Box167': 'Check Box167',
        'Text168': 'Text168',
        'Check Box169': 'Check Box169',
        'Check Box170': 'Check Box170',
        'Check Box171': 'Check Box171',
        'Text172': 'Text172',
        'Check Box173': 'Check Box173',
        'Check Box174': 'Check Box174',
        'Check Box175': 'Check Box175',
        'Check Box176': 'Check Box176',
        'Check Box177': 'Check Box177',
        'Check Box178': 'Check Box178',
        'Check Box179': 'Check Box179',
        'Check Box180': 'Check Box180',
        'Check Box181': 'Check Box181',
        'Check Box182': 'Check Box182',
        'Check Box183': 'Check Box183',
        'Text184': 'Text184',
        'Text185': 'Text185',
        'Text186': '186',
        'Text187': 'Text187',
        'Text188': 'Text188',
        'Text189': 'Text189',
        'Text190': '190',
        'Text191': 'Text191',
        'Text192': 'Text192',
        'Text193': 'Text193',
        'Text194': '194',
        'Text195': 'Text195',
        'Text19': 'Text19',
        'click': 'click',
        'click to': 'click to'
    };
};


const mergeFilledPDFs = async (formTypes, formData) => {
    const mergedPdf = await PDFDocument.create();
    const fieldMapping = buildFieldMapping(formData);

    for (const type of formTypes) {
        const pdfUrl = `/pdfs/${type}.pdf`;
        const res = await fetch(pdfUrl);

        if (!res.ok) {
            console.error(`❌ Failed to fetch PDF: ${pdfUrl}`);
            continue;
        }

        const pdfBytes = await res.arrayBuffer();
        const pdfDoc = await PDFDocument.load(pdfBytes);

        try {
            const form = pdfDoc.getForm();
            const fields = form.getFields();

            console.log(`[${type}] Field Names:`, fields.map(f => f.getName()));

            fields.forEach((field) => {
                const name = field.getName();
                const value = fieldMapping[name];

                if (value === undefined) return;

                try {
                    if (field instanceof PDFTextField && typeof value === 'string') {
                        field.setText(value);
                    } else if (field instanceof PDFCheckBox && value) {
                        value ? field.check() : field.uncheck();
                    } else if (field instanceof PDFRadioGroup && typeof value === 'string') {
                        field.select(value);
                    } else {
                        console.warn(`⚠️ Skipping field "${name}" of type ${field.constructor.name}`);
                    }
                } catch (e) {
                    console.warn(`Could not fill field ${name}:`, e.message);
                }
            });
        } catch (err) {
            console.warn(`No fillable form in ${type}:`, err.message);
        }

        const filledBytes = await pdfDoc.save();
        const loadedFilledPdf = await PDFDocument.load(filledBytes);
        const pages = await mergedPdf.copyPages(loadedFilledPdf, loadedFilledPdf.getPageIndices());
        pages.forEach((page) => mergedPdf.addPage(page));
    }

    return await mergedPdf.save();
};



export async function handleOnPDF() {
    try {
        const savedForm = localStorage.getItem("formStates");
        const savedSenerio = localStorage.getItem("senerio");

        const form = JSON.parse(savedForm || "{}");
        const senerio = JSON.parse(savedSenerio || "{}");
        let formTypes = [];

        if (senerio.includes('Disabled Person Placards/Plates')) {
            formTypes = ['REG195'];
        } else if (
            senerio.includes('Personalized Plates (Order)') ||
            senerio.includes('Personalized Plates (Reassignment)') ||
            senerio.includes('Personalized Plates (Replacement)') ||
            senerio.includes('Personalized Plates (Exchange)')
        ) {
            formTypes = ['REG17'];
        } else if (
            senerio.includes("Filing for Planned Non-Operation (PNO)") ||
            senerio.includes('Certificate Of Non-Operation')
        ) {
            formTypes = ['REG102'];
        } else if (senerio.includes('Add Lienholder')) {
            formTypes = ['Reg227'];
        } else if (senerio.includes('Remove Lienholder')) {
            formTypes = ['Reg227', 'DMVReg166'];
        } else if (senerio.includes('Duplicate Title')) {
            formTypes = ['Reg227'];
        } else if (
            senerio.includes('Duplicate Registration') ||
            senerio.includes('Duplicate Plates & Stickers') ||
            senerio.includes('Duplicate Stickers')
        ) {
            formTypes = ['Reg156'];
        } else if (senerio.includes('Name Change')) {
            formTypes = ['Reg256'];
        } else if (senerio.includes('Change Of Address')) {
            formTypes = ['DMV14'];
        } else if (senerio.includes('Salvage')) {
            formTypes = ['Reg488c'];
        } else if (senerio.includes('Restoring PNO Vehicle to Operational')) {
            formTypes = ['Reg256'];
        } else if (senerio.includes('Commercial Vehicle')) {
            formTypes = ['Reg343', 'Reg4008', 'Reg256'];
        } else {
            formTypes = ['DMVREG262', 'Reg227'];
            if (
                form.transactionSelections?.includes('Family Transfer') ||
                form.transactionSelections?.includes('Vehicle is a Gift') ||
                form.transactionSelections?.includes('Smog Exemption')
            ) {
                formTypes.push('Reg256');
            }
            if (form.transactionSelections?.includes('Out of State Title')) {
                formTypes.push('Reg343');
            }
        }

        const mergedBytes = await mergeFilledPDFs(formTypes, form);
        const blob = new Blob([mergedBytes], { type: 'application/pdf' });
        const url = URL.createObjectURL(blob);
        window.open(url);
    } catch (e) {
        console.error("error in genrating pdf : ", e)
    }
}